### ISSUE TITLE
Force build/install needed?

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/django-axes-deb#10]
https://github.com/freedombox/django-axes-deb/blob/e0e577bc6e28a5c0769342c9acb4335a95c7e8f4/debian/rules#L14

Is --force needed for build and install commands?

**Comment by JosephKiranBabu** [comment]
Looks like trusting stdeb to generate rules and other files is a huge mistake.
I'll go through all the debian files once again and see if anything unnecessary like this is generated.

**Comment by JosephKiranBabu** [comment]
Setuptools doesn't install older files over new files by default. 
The `--force` option for `build` and `install` are to ensure that the files from this package get installed over any new files that the user might already have. 
The deb package replacing any manually installed files is expected, isn't it?
I think the `--force` option is a good thing.

@jvalleroy Do you see any problems with it?

**Comment by jvalleroy** [comment]
@JosephKiranBabu dh_auto_build and dh_auto_install both happen during package build, not package install. dh_auto_install is installing files into a build directory that will become part of the package.

Anyway, I use cowbuilder to build in a clean environment every time, so it doesn't matter for me. I guess we can check whether other python packages use these options.

**Comment by jvalleroy** [comment]
Removed in #11.
