### ISSUE TITLE
Please add upstream and pristine-tar branches

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/django-axes-deb#2]
At least, git-buildpackage expects these branches.

The upstream branch would just contain the 1st commit in this repository (before /debian was added).

The pristine-tar branch can then be created as follows:
```
pristine-tar commit ../django-axes_2.3.3.orig.tar.gz
```
where django-axes_2.3.3.orig.tar.gz is what was originally unpacked as the initial commit.

**Comment by JosephKiranBabu** [comment]
Sorry, I didn't realize all the branches weren't pushed. I had all 3 branches on my local repository.
