### ISSUE TITLE
Miscellaneous suggestions

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/django-axes-deb#3]
- [ ] Update Standards-Version to 4.1.0.
- [x] New Homepage seems to be https://github.com/jazzband/django-axes.
- [x] Consider changing debian/ license to MIT, so that patches can be submitted upstream.
- [x] Add header paragraph to copyright file (https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/#header-paragraph)
- [x] Refer to MIT license as "Expat" and include full license text from upstream.
- [x] Add debian/watch file.

**Comment by JosephKiranBabu** [comment]
Fixes are in ed10057fe0e5c12faa08c160c6ee2a8fe2190f7c

**Comment by jvalleroy** [comment]
Standards-Version 4.0.0 is probably ok. 4.1.0 is released as policy, but lintian was not updated to support it yet.
