### ISSUE TITLE
Missing docs

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/django-axes-deb#9]
The docs are in the upstream repo, but not in the pypi release tarball. Ask upstream to consider including it.

**Comment by jvalleroy** [comment]
This can also be solved by importing the release from github, not from pypi. (The current watch file points to github releases, anyway.)

**Comment by JosephKiranBabu** [comment]
@jvalleroy I created another git repository, imported the tarball from Github and copied over the debian files that we've already created. Did a force push of all the branches to this remote, so that they'll have the content from the new tarball.

**Comment by jvalleroy** [comment]
@JosephKiranBabu Thanks! We should also add a python-django-axes-doc binary package, that installs the docs. Example: https://sources.debian.net/src/python-django/1:1.11.4-1/debian/control/#L128

**Comment by JosephKiranBabu** [comment]
@jvalleroy I tried to generate Sphinx docs with inspiration from django's own deb package.
There are still some problems. My work is on the branch `doc` in this repository. Created a pull request. #11 
Please continue work on the branch as I will not be available for the next 5 days.

**Comment by jvalleroy** [comment]
Merged #11 with some fixes.
